# Use the official Python image
FROM python:3.10-slim

# Set working directory in the container
WORKDIR /app

# Copy everything from your local folder into the container
COPY . .

# Run the script
CMD ["python", "app.py"]
